Update _encoders.py
missing ability to pass through `handle_unknown` argument

minimal reproducible case:
```
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd
import numpy as np
categories= np.asarray(['1', '4'], dtype=object)
df = pd.DataFrame(np.array([['1'], ['4'], ['7']], dtype=object), columns=['a'])
oe = OrdinalEncoder(categories=[categories], dtype=object, handle_unknown='use_encoded_value', unknown_value=100000)
new_col = oe.fit_transform(df['a'].values.reshape(-1, 1))
```
error: 
```
Traceback (most recent call last):
  File "/somepath/228/plugins/python/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/somepath/228/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/somepath/scratch.py", line 8, in <module>
    new_col = oe.fit_transform(df['a'].values.reshape(-1, 1))
  File "/somepath/anotherpath/venv/lib/python3.8/site-packages/sklearn/base.py", line 699, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/somepath/anotherpath/venv/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py", line 761, in fit
    self._fit(X)
  File "/somepath/anotherpath/venv/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py", line 109, in _fit
    raise ValueError(msg)
ValueError: Found unknown categories ['7'] in column 0 during fit
python-BaseException
```

using: 
python3.8
scikit-learn 0.24.1