Fix unset local variable due to missing else
Add an else clause that raises a TypeError to avoid the following
error when passing a wrong type:

File "...sklearn/model_selection/_split.py", line 1849, in
_validate_shuffle_split
n_train = n_samples - n_test
UnboundLocalError: local variable 'n_test' referenced before assignment