Change 'scale' to 'auto' in example
Example returns TypeError:
"sklearn/svm/libsvm.pyx in sklearn.svm.libsvm.fit()
TypeError: a float is required"
Change to auto because 'scale' deprecated:
"The current default of gamma, 'auto', will change to 'scale' in version 0.22. 'auto_deprecated', a deprecated version of 'auto' is used as a default indicating that no explicit value of gamma was passed."