FIX PermissionError in datasets fetchers on Windows
PermissionError: [WinError 32] The process cannot access the file
because it is being used by another process. This was happening when
trying to remove the downloaded archive because the archive was not
properly closed.