Clearer exception on legacy multi-label data representation
Motivating example:

```python
>>> from sklearn.metrics import hamming_loss
>>> expt_list = [["A"], ["B"], ["C"], ["D"], ["E"], ["A", "E"]]
>>> pred_list = [["A"], ["B"], ["B", "C"], ["C"], ["E"], ["A"]]
>>> hamming_loss(expt_list, pred_list)
Traceback (most recent call last):
...
ValueError: You appear to be using a legacy multi-label data representation. Sequence of sequences are no longer supported; use a binary array or sparse matrix instead.
```

I would have found it helpful if the exception mentioned the new helper class ``MultiLabelBinarizer``, used as follows:

```python
>>> from sklearn.metrics import hamming_loss
>>> from sklearn.preprocessing import MultiLabelBinarizer
>>> expt_list = [["A"], ["B"], ["C"], ["D"], ["E"], ["A", "E"]]
>>> pred_list = [["A"], ["B"], ["B", "C"], ["C"], ["E"], ["A"]]
>>> relabel = MultiLabelBinarizer(["A", "B", "C", "D", "E"])  # 5 classes
>>> expt = relabel.fit_transform(expt_list)
>>> pred = relabel.fit_transform(pred_list)
>>> hamming_loss(expt, pred)
0.13333333333333333
```